\documentclass[12pt,a4paper,twoside]{article}
%-------------------------------------------------------------
% Preambulo

\usepackage{graphicx,hyperref,amsmath,natbib,bm,url,microtype}
\usepackage[spanish]{babel}
\usepackage[a4paper,text={16.5cm,25.2cm},centering]{geometry}
\usepackage[compact,small]{titlesec}
\usepackage[utf8]{inputenc}

\setlength{\parskip}{1.2ex}
\setlength{\parindent}{0em}
\clubpenalty = 10000
\widowpenalty = 10000


%--------------------------------------------------------------
\begin{document}
%\SweaveOpts{concordance=TRUE}
%--------------------------------------------------------------


\begin{itemize}



\item Muestra el codigo pero no los resultados: 

<<echo=TRUE, results='hide' >>=
1 + 1
@

\item Muestra solo los resultados:

<<echo=FALSE, results='markup'  >>=
1 + 1
@

\item Muestra el codigo y los resultados:

<<echo=TRUE, results='markup'  >>=
1 + 1
@

\item Muestra el codigo (sobre fondo gris) y los resultados (sin fondo gris):

<<echo=TRUE, results='asis'  >>=
1 + 1
@

\item Descarta los graficos

<<echo=TRUE, results='markup', fig.keep='none' >>=
x <- rnorm(5)
print(x)
boxplot(x)
@

\item No descarta el grafico

<<echo=TRUE, results='markup', fig.keep='all' >>=
x <- rnorm(50)
boxplot(x)
@

\item No descarta el grafico y controla su tamaño y posicion:

<<echo=TRUE, results='markup', fig.keep='all', fig.width=5 , fig.height=3 , fig.align='center' >>=
x <- rnorm(50)
boxplot(x)
@

\end{itemize}

\end{document}
